<Project Sdk="Aspire.AppHost.Sdk/13.5.2">

  <ItemGroup>
    <ProjectReference Include="..\CacheApi\CacheApi.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>c3e5a7b9-4d6f-4a8b-8c2e-4f6a8b0d2f1e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.5.2" />
  </ItemGroup>

</Project>
