-- 19-cleanup.sql: sprzatanie baz demo i sesji XE
SET NOCOUNT ON;
USE master;
GO
IF EXISTS (SELECT 1 FROM sys.server_event_sessions WHERE name = 'psp_diag') DROP EVENT SESSION psp_diag ON SERVER;
GO
IF DB_ID('PspLab') IS NOT NULL BEGIN ALTER DATABASE PspLab SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE PspLab; END
IF DB_ID('NcciClean') IS NOT NULL BEGIN ALTER DATABASE NcciClean SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE NcciClean; END
GO
