-- 10-cleanup.sql
SET NOCOUNT ON;
IF EXISTS (SELECT 1 FROM sys.server_event_sessions WHERE name = 'psp_multi') DROP EVENT SESSION psp_multi ON SERVER;
GO
IF DB_ID('PspMulti') IS NOT NULL
BEGIN
    ALTER DATABASE PspMulti SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE PspMulti;
END
IF DB_ID('StaleLab') IS NOT NULL
BEGIN
    ALTER DATABASE StaleLab SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE StaleLab;
END
GO
