// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PgVectorEfMigrations;
using Pgvector;

#nullable disable

namespace PgVectorEfMigrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929024410_BumpHnswParams")]
    partial class BumpHnswParams
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PgVectorEfMigrations.Item", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(64)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Embedding" }, "ix_items_embedding_hnsw")
                        .HasAnnotation("Npgsql:StorageParameter:ef_construction", 128)
                        .HasAnnotation("Npgsql:StorageParameter:m", 24);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Embedding" }, "ix_items_embedding_hnsw"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Embedding" }, "ix_items_embedding_hnsw"), new[] { "vector_cosine_ops" });

                    b.ToTable("items", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
