<Project Sdk="Aspire.AppHost.Sdk/13.5.2">

  <ItemGroup>
    <ProjectReference Include="..\CacheApi\CacheApi.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>d4f6b8ca-5e70-4b9c-9d3f-5a7b9c1e3a2f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.5.2" />
  </ItemGroup>

</Project>
