-- 10-cleanup.sql - opcjonalnie: usuwa obie bazy demo.
USE master;
GO
IF DB_ID('PrasowkaLock') IS NOT NULL BEGIN ALTER DATABASE PrasowkaLock SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE PrasowkaLock; END
IF DB_ID('PrasowkaCS')   IS NOT NULL BEGIN ALTER DATABASE PrasowkaCS   SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE PrasowkaCS;   END
GO
