// Dosłowna zawartość .teamcity/patches/buildTypes/Hello.kts z commita d93a614 (po DWÓCH zmianach z REST/UI).
// Pierwszy commit serwera (eba27b2) zawierał tylko blok expectSteps/steps; blok params doszedl po drugiej zmianie.
package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Hello'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Hello")) {
    params {
        expect {
            param("greeting", "hallo")
        }
        update {
            param("greeting", "czesc")
        }
    }

    expectSteps {
        script {
            name = "Greet"
            scriptContent = "echo hello-v2 %greeting%"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()
            scriptContent = "echo hello-from-rest %greeting%"
        }
    }
}
